### ISSUE TITLE
mid presentation lessons learned

### ISSUE THREAD

**Issue by sylee0124** [swsnu/swpp2019-team9#30]
원하는시는걸 comment로 달아주세요

**Comment by sylee0124** [comment]
Software development 단순히 기능을 구현하는것 보다 훨씬 생각해야할 부분이 많다.
왠만하면 새로 만들생각하지 말고 있는 것들을 잘 찾아서 활용해야겠다.

**Comment by wormfry** [comment]
개발을 하기 전에 팀과 상의를 하여 어떤 기능을 만들고 어떤 api를 제공할지 충분히 계획을 짜야지 결과적으로 시간을 아낄 수 있다

**Comment by YooYoungJae** [comment]
팀간 업무 분배에 선을 긋는게 쉽지 않다. 팀간 소통을 원활히 하기 위해 공통된 문서를 작성해 나가는게 중요하다.

**Comment by manhair** [comment]
계획은 생각보다 훨씬 더 넉넉하게 잡는게 좋다
