### ISSUE TITLE
Group Comment delete issue

### ISSUE THREAD

**Issue by sylee0124** [swsnu/swpp2019-team9#33]
현재 comment model을 구현할때 user 그리고 group에 대해서 foreignkey로 구현을 하였습니다.
그런데 이 구현의 경우 user가 group을 나갈때는 comment가 삭제되지 않는 문제가 있는데 (group이 없어지거나 user가 없어진게 아니라서) 이런 문제는 어떻게해야 handle할수 있는지 
혹시 아시는분 이나 방향을 제시해주실 분 있으신가요?

**Comment by sylee0124** [comment]
group과 user 중간에 model을 만들까요?

**Comment by YooYoungJae** [comment]
group 과 user 중간에 group_member 라는 모델 있습니다!
