### ISSUE TITLE
Signup related api/testing discussion

### ISSUE THREAD

**Issue by sylee0124** [swsnu/swpp2019-team9#4]
1) planning to make /api/signup/ for ID checking
2) when testing get it have some issues : mocked to return 200 but seems to return 404
3) have styling issue for warning messages
![image](https://user-images.githubusercontent.com/47180088/67558499-139dd300-f752-11e9-8842-1dd9a8df0278.png)
공백을 넣고 싶은데 어떻게 해야할까요... css로 해야하는 건가요??

**Comment by YooYoungJae** [comment]
넵넵 css 로 하는게 제일 날듯 합니다.!

**Comment by YooYoungJae** [comment]
@sylee0124 아니요 그런걸 정한 바는 없었습니다. signup 시 login 창으로 이동시켜서 login 하도록 유도하는게 좋지 않을까요?
