### ISSUE TITLE
처음 메인페이지에서, 왼쪽 오른쪽 넘어가는 사진(?)에서의 오류

### ISSUE THREAD

**Issue by kanghc0217** [swsnu/swpp2019-team9#69]
왼쪽 상단에 show camara 버튼 있는 사진에서,
왼쪽 부분을 눌러도 사진이 오른쪽으로 넘어갑니다.

![image](https://user-images.githubusercontent.com/40143716/70224412-94f47680-1790-11ea-936e-35f022016c29.png)

**Comment by kanghc0217** [comment]
뭔가 순서가 꼬여있는 것 같습니다.

**Comment by sylee0124** [comment]
그게 첫사진에서 왼쪽으로 가려하면 가장 끝 사진으로 가는데 그때 넘어가는 애니메이션이 오른쪽으로 가는것 같습니다. 감사합니다
